[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "chapter-6"
version = "0.1"
dependencies = ["numpy.testing", "pytest", "numpy"]

[tool.hatch.build.targets.wheel]
packages = ["nonlinear_solvers"]
